### ISSUE TITLE
Google docs (cello) parsing throws json_extract error on query

### ISSUE THREAD

**Issue by ydkhatri** [abrignoni/ALEAPP#94]
Apparently, on windows only Python 3.9 ships with a version of sqlite that supports/enables json querying. Older versions throw this error:
```
Google Docs [Cello] artifact executing
Reading Google Docs artifact had errors!
Error was no such function: json_extract
Exception Traceback: Traceback (most recent call last):
  File "c:\github\ALEAPP\scripts\ilap_artifacts.py", line 164, in process_artifact
    method(files_found, report_folder, seeker)
  File "c:\github\ALEAPP\scripts\artifacts\Cello.py", line 84, in get_Cello
    ''')
sqlite3.OperationalError: no such function: json_extract
```

Need to refactor query to fix this.

**Comment by stark4n6** [comment]
This was fixed I think with the Python update, correct me if I'm wrong

**Comment by ydkhatri** [comment]
If you run with python < 3.9, it will still produce the exception, as no action was taken. However, since we now recommend 3.9, I am not inclined to spend time to fix it. The issue remains open as it is not fixed.

**Comment by stark4n6** [comment]
makes sense to me
